# Generated by Django 4.0.5 on 2023-11-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
