# Generated by Django 4.0.5 on 2023-11-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_datetime_event_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
