# Generated by Django 4.0.5 on 2023-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
