# Generated by Django 4.0.5 on 2023-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=40)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Science', 'Information Science'), ('Electrical and Electronics', 'Electrical and Electronics'), ('Elecronics and Communication', 'Elecronics and Communication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=30, verbose_name='Select Branch')),
                ('year', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Select Year')),
            ],
        ),
    ]
