# Generated by Django 4.0.5 on 2023-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_student_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='roll_number',
            field=models.CharField(max_length=10),
        ),
    ]
