# Generated by Django 4.0.5 on 2023-11-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_student_register_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='year',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth')], verbose_name='Select Year'),
        ),
    ]
