# Generated by Django 4.0.5 on 2023-11-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_student_register_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
