# Generated by Django 4.0.5 on 2023-11-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
