# Generated by Django 4.0.5 on 2023-11-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
