# Generated by Django 4.0.5 on 2023-11-29 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_registration_deadline_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 29, 8, 31, 55, 477035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 8, 31, 55, 477035, tzinfo=utc)),
        ),
    ]
