# Generated by Django 4.0.5 on 2023-11-29 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_start_time_alter_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 8, 35, 6, 635136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 29, 8, 35, 6, 635136, tzinfo=utc)),
        ),
    ]
